# SPDX-FileCopyrightText: 2026 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

standa_sat_files = files(
  '__init__.py',
  '__main__.py',
  'Standa.py',
  'motor_controller.py',
  'stage_config.py',
)

py.install_sources(standa_sat_files,
  subdir: 'constellation/satellites/Standa'
)
